def one(): print(1, end="")
def two(): print(2, end="")
def there(): print(3, end="")
def four(): print(4, end="")
def five(): print(5, end="")
def six(): print(6, end="")
def seven(): print(7, end="")
def eight(): print(8, end="")
def nine(): print(9, end="")
def zero(): print(0, end="")

eight(), eight(), zero(), zero(), five(), five(), five(), there(), five(), there(), five()